course = 'haaga-helia-python-2022'
[exercises.osa01-01_hymio]
id = 153838
checksum = '65d51cdf55a795fb0c7b4f101a35a669'

[exercises.osa01-02_ukko_nooa]
id = 153840
checksum = '958609e3628463c2416110a9e429bc74'

[exercises.osa01-03_korjaa_ohjelma_7_veljesta]
id = 153842
checksum = '3f7cc983a4d8ef37bffbd80fa81f1499'

[exercises.osa01-04_minuuttien_maara_vuodessa]
id = 153850
checksum = '877191d9d6b8a878a957191579429147'

[exercises.osa01-05_ohjelma_tulostaa_koodia]
id = 153829
checksum = 'a3966c197ade625d46be69193c4b84f7'

[exercises.osa01-06_nimi_kahdesti]
id = 153845
checksum = '1c5971a2e8b9b4210df9433f28798b2e'

[exercises.osa01-07_nimi_ja_huutomerkit]
id = 153854
checksum = 'ad78ed491524469c91e546fd07493448'

[exercises.osa01-08_nimi_ja_osoite]
id = 153852
checksum = '87538c4f1f3097c87eb3971376bdf30a'

[exercises.osa01-09_korjaa_ohjelma_lausahdukset]
id = 153853
checksum = 'b81da07c859cbe98add4296e7864be48'

[exercises.osa01-10_tarina]
id = 153841
checksum = '9862423ae21f06b30c6afdbfe6f42ac0'

[exercises.osa01-10b_valilyonnilla_vai_ilman]
id = 153824
checksum = '25b48ee01d2275e6e5e4a8a643dc5bda'

[exercises.osa01-11_laskutoimitukset]
id = 153830
checksum = '5d4b50330200556c30685c46718819f9'

[exercises.osa01-12_korjaa_ohjelma_tulostukset_samalle_riville]
id = 153825
checksum = 'c01be32636c9906b7b7d8d93ed6979a9'

[exercises.osa01-13_kerrottuna_viidella]
id = 153839
checksum = '9b4f17b02b7a7192364dbec6afa426b0'

[exercises.osa01-14_nimi_ja_ika]
id = 153837
checksum = '2a7e6289d53ef7342d1ec3a6aba6b3e9'

[exercises.osa01-15_sekunteja_vuorokaudessa]
id = 153843
checksum = '3111882e190977e135602710bf742235'

[exercises.osa01-16_lukujen_summa_ja_tulo]
id = 153851
checksum = '8808f7627c1ef390e992fb5d8caf2e6f'

[exercises.osa01-17_lukujen_summa_ja_keskiarvo]
id = 153832
checksum = '03c92d7732b25449a5dcfe1456ec735c'

[exercises.osa01-18_opiskelijat_ryhmiin]
id = 153844
checksum = '3a5e1ac99ac7bdf77d71e51d192ca311'

[exercises.osa01-19_ruokailukustannukset]
id = 153826
checksum = '0a5255f3820d13945012edf4e0f75998'

[exercises.osa01-20_korjaa_ohjelma_lukujen_tulo]
id = 153831
checksum = 'f48147655122044438ce21f57664ea52'

[exercises.osa01-21_orwel]
id = 153849
checksum = 'b8ad85cdda51d4182938f73f7159f498'

[exercises.osa01-22_itseisarvo]
id = 153848
checksum = '115dcecdd5fb1781b537604433768e4e'

[exercises.osa01-23_keittoa_vai_ei]
id = 153836
checksum = 'b5aad36fa007dce78105b4fd3b3034c3'

[exercises.osa01-24_luvun_suuruusluokka]
id = 153833
checksum = 'a7fdd11c41b42d9b1d3564ea0b743209'

[exercises.osa01-25_laskin]
id = 153846
checksum = '9ab286e5d242991966e6fe70270accc8'

[exercises.osa01-26_lampotilat]
id = 153834
checksum = '3aa32d9dd4cb3545300acfb2baa30ec4'

[exercises.osa01-27_palkka]
id = 153847
checksum = '8e2bf0c02256965479f35a4ede91f0f9'

[exercises.osa01-28_korjaaa_ohjelma_korkoa_kortille]
id = 153828
checksum = '05fe0dc3dec32f8c0c2910e0e12ac64a'

[exercises.osa01-29_huomisen_vaatteet]
id = 153835
checksum = '5ae35bdcec9fa604ac152bdbcf56f914'

[exercises.osa01-30_toisen_asteen_yhtalo]
id = 153827
checksum = '6c8e1b6ba30a391e71f48b8b1d71ea50'

[exercises.osa02-01_korjaa_virheet]
id = 153739
checksum = 'f07b10144634d1b35933cfb2f9d94df0'

[exercises.osa02-02_merkkien_maara]
id = 153747
checksum = '9b6db02d0501d78db37ece32bd7668df'

[exercises.osa02-03_tyyppimuunnos]
id = 153746
checksum = '578c453d084f40a37e1580ca80891db2'

[exercises.osa02-04_taysi_ikaisyys]
id = 153728
checksum = '049aa9af398e70528d3d411769f436b2'

[exercises.osa02-05_suurempi_tai_yhtasuuri]
id = 153745
checksum = '7308f6a451a5165d13d04c1f8ce47df4'

[exercises.osa02-06_vanhempi]
id = 153730
checksum = '7c69e9aa1b719dc995590c4adbed8d1b'

[exercises.osa02-07_aakkkosjarjestyksessa_viimeinen]
id = 153733
checksum = '161308c8292fac20efe9fbed6ad4edfd'

[exercises.osa02-08_ian_tarkistus]
id = 153744
checksum = '008d796c9c57ba63ee84e03e3f3d4a3c'

[exercises.osa02-09_veljenpojat]
id = 153741
checksum = '2b00e1f44624423caa1c738080ad5edb'

[exercises.osa02-10_arvosana_ja_pisteet]
id = 153735
checksum = 'fe087098a1ac4b15096b38fc5d978dee'

[exercises.osa02-11_fizzbuzz]
id = 153727
checksum = '7f6e2ee78c7f525fe1fbc595feb77658'

[exercises.osa02-12_karkausvuosi]
id = 153731
checksum = '69cb206369cac5fd9c62c78f3102ef97'

[exercises.osa02-13_aakkosjarjestyksessa_keskimmainen]
id = 153729
checksum = '90588e3901577a8584852b9c95012d58'

[exercises.osa02-14_lahjaverolaskuri]
id = 153736
checksum = '087844c603d7d8eed3b5b8393520c51a'

[exercises.osa02-15_jatketaanko]
id = 153743
checksum = '8ae6a99595f805760b68377fed76df12'

[exercises.osa02-16_syotteen_rajaus]
id = 153738
checksum = '0dede6febb14f3517e8abc2418bedcb2'

[exercises.osa02-17_lahtolaskenta]
id = 153742
checksum = 'b04dbff530e8d57efeed0c634b9ee7ad'

[exercises.osa02-18_salasana_uudelleen]
id = 153732
checksum = '167189e2edca56afde7d5c108d73b5ce'

[exercises.osa02-19_pin_ja_yritysten_maara]
id = 153737
checksum = 'b67a945b132384a3859d260854f4c3ef'

[exercises.osa02-20_seuraava_karkausvuosi]
id = 153740
checksum = 'd325a46695709604d1f75d646afaa165'

[exercises.osa02-21_tarina]
id = 153726
checksum = '65bf3c3ed941beafa0d99af734a45a97'

[exercises.osa02-22_lukujen_kasittelya]
id = 153734
checksum = '6c1ebe441d83e2200881a4e57eaf7a9a'

[exercises.osa03-00_tulosta_luvut]
id = 153885
checksum = 'a040ecf48b3b6fe20cf2f3c8fe6efbe4'

[exercises.osa03-01_lahtolaskenta]
id = 153887
checksum = 'f183bb4dc910fe0a7d356de91d7776ee'

[exercises.osa03-02_luvut]
id = 153857
checksum = 'd2a7f8756d2e9be15d695fcb0102879e'

[exercises.osa03-03_kahden_potenssit]
id = 153866
checksum = '7cf9c3e12acccf6cf58a4d7174555aba'

[exercises.osa03-04_luvun_n_potenssit]
id = 153878
checksum = 'bc8ba2d951fcf4656b3644f96926c9a5'

[exercises.osa03-04a_perakkaisten_summa_helpompi]
id = 153862
checksum = 'b94f9c6380ca7bd7a7dec30a945b3837'

[exercises.osa03-05_perakkaisten_summa]
id = 153865
checksum = 'c4128f7196035e051cbe8dd0167462d7'

[exercises.osa03-05a_monistetut_jonot]
id = 153874
checksum = '47854dacc4a9c9757e4a16f87637762c'

[exercises.osa03-05b_pidempi_jono]
id = 153872
checksum = 'ab98ea4fadfc416ebefd403a7b496e6a'

[exercises.osa03-05c_lopusta_alkuun]
id = 153886
checksum = '73652cf27735899d00e664a5714acd5f'

[exercises.osa03-06_toinen_ja_toiseksi_viimeinen]
id = 153875
checksum = '1f49fc38796237ca4477e9ecb6bcb401'

[exercises.osa03-07_osajonot1]
id = 153873
checksum = '3c321e327c930beadf8a0e6f2f246e24'

[exercises.osa03-08_osajonot2]
id = 153877
checksum = 'b08799c1dbe058b8b0a2c547a4f2b144'

[exercises.osa03-09_risuaitaviiva]
id = 153863
checksum = 'e4976ebd5ea7b386ee00aa170b8e9f38'

[exercises.osa03-10_risuaitanelio]
id = 153870
checksum = '60b6699b50741a574e04116b18bba051'

[exercises.osa03-11_alleviivaus]
id = 153871
checksum = '2879472e1895d69d4b0a8fe983ab0887'

[exercises.osa03-12_tasaus_oikeaan]
id = 153860
checksum = 'c85fd2a0846ac4630b3dc02d9c90c3dc'

[exercises.osa03-13_sanalaatikko]
id = 153881
checksum = 'fd19e319e989a23be7cd3000daa7c360'

[exercises.osa03-13b_loytyvatko_vokaalit]
id = 153882
checksum = '0e667f8f0127920c86d9e220d71b0614'

[exercises.osa03-13c_osajonon_haku]
id = 153868
checksum = 'ffbea8d45be7692356a953853c435f1f'

[exercises.osa03-14_osajonojen_haku]
id = 153856
checksum = '2ff670ec11c9e8ee911a7737cf7b2df1'

[exercises.osa03-15_toinen_esiintyma]
id = 153869
checksum = '6e16b016ca168b719c30100736858edf'

[exercises.osa03-15b_kertotaulut]
id = 153855
checksum = '98ec530578ceaf9872439d822b52e9c6'

[exercises.osa03-16_sanojen_ensimmaiset_kirjaimet]
id = 153864
checksum = '1d4d0869b28a0b379c33fab97d0aca6f'

[exercises.osa03-17_kertomat]
id = 153858
checksum = '6310ad569280d86bed383b215a8d7567'

[exercises.osa03-18_parit_ympari]
id = 153888
checksum = '90d6a174735559f0e2adbe25233f2d98'

[exercises.osa03-19_vuorotellen]
id = 153884
checksum = '1e301c513845f27b31edf69845eac4ca'

[exercises.osa03-21_seitseman_veljesta]
id = 153880
checksum = '2c6c2c07e7a9c35305b34e8b85a16be7'

[exercises.osa03-22_ensimmainen_merkki]
id = 153859
checksum = '17f4c0293425ce589eae45641bbb8584'

[exercises.osa03-23_risunelio]
id = 153883
checksum = 'ba0b3262d32d46b0be631f5283f6e500'

[exercises.osa03-24_monta_tulostusta]
id = 153861
checksum = 'fdf7a763e029dee7be68eac6184cd5fa'

[exercises.osa03-25_keskiarvo]
id = 153867
checksum = '7e56932aced958f813b5c374b283a501'

[exercises.osa03-26_shakkilauta]
id = 153876
checksum = 'c4ee67c1067dfa5962e01be249c23d20'

[exercises.osa03-27_sananelio]
id = 153879
checksum = '5ab854fc8591bee8d2bae3491fc43e72'

[exercises.osa04-01_hello_visualstudio_code]
id = 153671
checksum = '94031d5eca58d4816aad2d2dcf96147d'

[exercises.osa04-02_viiva]
id = 153661
checksum = '24e10d12cb3dc2ed6f7e7dacb7c6195e'

[exercises.osa04-02a_risulaatikko]
id = 153669
checksum = '1fb48095046d82723f9d086b04dc0978'

[exercises.osa04-02b_risunelio]
id = 153670
checksum = '7ee4abde2c0bd4613dfe85d5f0a39ca6'

[exercises.osa04-02c_nelio]
id = 153675
checksum = '5cff2ebb602cda17d0201b9c5b67a923'

[exercises.osa04-02d_kolmio]
id = 153653
checksum = '7ef0cf95ff9c819ec896a7d27b2ee6a5'

[exercises.osa04-03_kuvio]
id = 153660
checksum = '3f2421c0c4d4af11fc48671b77cc8a9b'

[exercises.osa04-04_joulukuusi]
id = 153657
checksum = 'c5c1dcbc98a13b98838049f9ddea49c9'

[exercises.osa04-05_luvuista_suurin]
id = 153650
checksum = '50d744e6b4ea69ddfadfb2fce2cdec6c'

[exercises.osa04-06_merkit_samat]
id = 153646
checksum = 'dae82454fdff16d006bcd830346c7e14'

[exercises.osa04-07_eka_toka_vika_sana]
id = 153664
checksum = '8efff960ceb4f03f9a385aefb225cfaf'

[exercises.osa04-07a_alkioiden_arvojen_muutokset]
id = 153666
checksum = '2c479ae982981cb08e03aecdc2fe81e9'

[exercises.osa04-07b_alkoiden_lisays_listaan]
id = 153668
checksum = '2fe4414ba779f516d5869992eba942e6'

[exercises.osa04-07c_lisays_ja_poisto]
id = 153665
checksum = '25b8b42ed716d37376aff375c515f24d'

[exercises.osa04-08_sama_sana_kahdesti]
id = 153672
checksum = '577975669bd3e321eaa5f36c3851165a'

[exercises.osa04-08b_lista_kahdesti]
id = 153658
checksum = '158f01cc689e98904094478f7babf3b4'

[exercises.osa04-09_listan_pituus]
id = 153649
checksum = 'e811d9090a3a94ba73bf9cee9b44b114'

[exercises.osa04-10_keskiarvo]
id = 153645
checksum = '4b48abeeb0b80518849a931b255c293b'

[exercises.osa04-11_vaihteluvali]
id = 153642
checksum = 'c210a00b2b10f2c0c8e7e77d57296e4f'

[exercises.osa04-11a_tulostus_tahdilla]
id = 153673
checksum = '135caf53fdb5c7e86c3625d1aa520539'

[exercises.osa04-11b_negatiivisesta_positiiviseen]
id = 153676
checksum = '452c30a3aca2ecfdb1f95f179e75dc10'

[exercises.osa04-12_tahdet]
id = 153659
checksum = 'e1d9bb5024bc391b1a1acd45f650b672'

[exercises.osa04-13_anagrammi]
id = 153648
checksum = '798034570e1a94a0a44c27c0fe9b090c'

[exercises.osa04-14_palindromit]
id = 153674
checksum = 'e3f02ea957f09bd7ecf569701a786cb9'

[exercises.osa04-15_positiivisten_summa]
id = 153654
checksum = '14ce9e752e8dd46df6ff57337abd0755'

[exercises.osa04-16_parilliset]
id = 153651
checksum = '8b003218b809dfe1d1a78405092ca13c'

[exercises.osa04-17_summalista]
id = 153652
checksum = '2a0762463c7a67d01fe1875d6d018d42'

[exercises.osa04-18_uniikit]
id = 153662
checksum = '43998b36195a7806b573ce24da040158'

[exercises.osa04-18a_listan_pimman_pituus]
id = 153647
checksum = '0aab032081d7490a0ec7932affc6011d'

[exercises.osa04-18b_listan_lyhin]
id = 153656
checksum = '6297dc8d8d856b8277ee6de0b98e9832'

[exercises.osa04-19_listan_pisimmat]
id = 153641
checksum = '73cd26585e24ca7fdcf96283323ada33'

[exercises.osa04-20_lukulistasta_merkkijonolistaksi]
id = 153643
checksum = 'd2dc66376d55240ad37720b98a2eb92b'

[exercises.osa04-21_kaikki_vaarinpain]
id = 153678
checksum = '954e325408dbdb683ccbaead9ebc6735'

[exercises.osa04-22_eniten_kirjaimia]
id = 153655
checksum = '8984d40a0ddfe675ffc7af980dd96511'

[exercises.osa04-23_vokaalit_pois]
id = 153644
checksum = 'ae6497a178f1b2491e670fe023eb112d'

[exercises.osa04-24_poista_isot]
id = 153677
checksum = '76fd0ba194753b69cc251a3b5e5ff3ea'

[exercises.osa04-25_naapureita_listassa]
id = 153667
checksum = 'b1106a52f9ef3727b035c989a4c878bc'

[exercises.osa04-26_arvosanatilasto]
id = 153663
checksum = '8f3a734741ddcd2b87a65fcd737ce211'
